#!/usr/bin/env node

'use strict'

const {default: yargs} = require('../../');
var parser = yargs(process.argv.slice(2))

console.log(parser.parserConfiguration({
    'dot-notation': false,
    'boolean-negation': false
}).parse())
