#!/usr/bin/env node

'use strict'

var parser = require('../../yargsa.js').yargsa(process.argv.slice(2))

console.log(parser.parserConfiguration({
    'dot-notation': false,
    'boolean-negation': false
}).argv)
