#!/usr/bin/env node

'use strict'

async function main() {
    var parser = require('../../yargs.js')(process.argv.slice(2))

    console.log(await parser.parserConfiguration({
        'dot-notation': false,
        'boolean-negation': false
    }).argv)
}

main()
